language: cpp
dist: xenial
compiler:
  - gcc
  # - clang 

addons: 
  apt: 
    packages: libboost-all-dev

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # SFML
  - sudo apt-get install libsfml-dev
  # clang-tidy
  - sudo apt-get install -qq clang-3.8
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # For the virtual X server
  - sudo apt-get install libxrandr-dev
  # valgrind, for helgrind and memcheck
  - sudo apt-get install -qq valgrind
  # SLOCcount
  - sudo apt-get install sloccount

services:
 - xvfb

script: 
  # Game logic non-SFML tests
  - qmake AminoAcidFighterTest.pro
  - make --silent debug
  - ./AminoAcidFighterTest
  # Game logic SFML tests
  - qmake AminoAcidFighterSfmlTest.pro
  - make --silent debug
  - ./AminoAcidFighterSfmlTest
  # Build and run profile run
  - qmake AminoAcidFighter.pro
  - make --silent release
  - time ./AminoAcidFighter --profile --no_music
  - gprof AminoAcidFighter > gprof.log
  - head gprof.log -n 100
  # cppcheck
  - cppcheck --error-exitcode=1 . 
  # Get code coverage
  - ./get_code_cov
  - codecov
  # Call OCLint
  - ./do_oclint
  # memcheck
  - valgrind --leak-check=full -v --show-reachable=yes --log-file=memcheck.log ./AminoAcidFighterTest
  - cat memcheck.log
  # SLOCcount
  #   remove OCLint otherwise it will be counted as well
  - rm -rf oclint-0.10.3
  - cd ..; sloccount --overhead 1 --personcost 22614 AminoAcidFighter; cd AminoAcidFighter
  # clang-tidy
  #- ./do_clang-tidy

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)
