sudo: require
language: cpp
compiler: gcc
# dist: trusty # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # SFML
  - sudo apt-add-repository ppa:sonkun/sfml-development -y
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # SFML
  - sudo apt-get install libsfml-dev
  # clang-tidy
  - sudo apt-get install -qq clang
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # Build and run tests
  - qmake AminoAcidFighterTest.pro
  - make debug
  - ./AminoAcidFighterTest
  # Build and run the real program
  - qmake AminoAcidFighter.pro
  - make
  - ./AminoAcidFighter &
  - sleep 10
  - sudo killall AminoAcidFighter
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Get code coverage
  - ./get_code_cov
  - codecov
  # clang-tidy
  - ./do_clang-tidy
  # Call OCLint
  - ./do_oclint

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)
