language: cpp
dist: bionic
compiler:
  - gcc
  # - clang 

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # SFML
  - sudo apt-get install libsfml-dev
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # For the virtual X server
  - sudo apt-get install libxrandr-dev
  # valgrind, for helgrind and memcheck
  - sudo apt-get install -qq valgrind
  # SLOCcount
  - sudo apt-get install sloccount
  # Check dead links
  #- sudo apt-get install -qq npm
  #- npm config set strict-ssl false
  #- sudo npm install -g markdown-link-check

services:
  - xvfb
  - alsa

script: 
  # Game logic non-SFML tests
  - qmake AminoAcidFighterTest.pro
  - make --silent debug
  - ./AminoAcidFighterTest
  # Game logic SFML tests
  - qmake AminoAcidFighterSfmlTest.pro
  - make --silent debug
  # Cannot run this test, do not know why
  # - ./AminoAcidFighterSfmlTest
  # Build and run profile run
  - qmake AminoAcidFighter.pro
  - make --silent release
  - time ./AminoAcidFighter --profile --no_music
  - gprof AminoAcidFighter > gprof.log
  - head gprof.log -n 100
  # cppcheck
  - cppcheck --error-exitcode=1 . 
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # Call OCLint
  - ./do_oclint || true
  # memcheck
  - valgrind --leak-check=full -v --show-reachable=yes --log-file=memcheck.log ./AminoAcidFighterTest
  - cat memcheck.log
  ## Check dead links
  #- rm .travis.yml
  #- ./scripts/check_dead_links || true
  # SLOCcount
  #   remove OCLint otherwise it will be counted as well
  - rm -rf oclint-0.10.3
  - cd ..; sloccount --overhead 1 --personcost 22614 AminoAcidFighter; cd AminoAcidFighter

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)
